# Generated by Django 3.0.4 on 2020-04-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.URLField(default='https://thefilmuniverse.com/wp-content/uploads/2019/09/Poster_Not_Available2.jpg', max_length=500),
        ),
    ]
